### ISSUE TITLE
drivers/input/touchscreen/ftxxxx_ex_fun.c  Compiler Error

### ISSUE THREAD

**Issue by abhishekr700** [CyanogenMod/android_kernel_asus_msm8916#1]
The following file return an error "label at end of compound statement switch" on lines 427 and 654 
A break statement is expected after the fall through.

**Comment by luk1337** [comment]
Works just fine here:

`Generating master DTB... completed
Made DT image: /mnt/android/cm-13.0/out/target/product/Z00T/dt.img
Target boot image:/mnt/android/cm-13.0/out/target/product/Z00T/boot.img
/mnt/android/cm-13.0/out/target/product/Z00T/boot.img maxsize=34197504 blocksize=135168 total=28309504 reserve=405504
Made boot image: /mnt/android/cm-13.0/out/target/product/Z00T/boot.img
make: Leaving directory '/mnt/android/cm-13.0/cm-13.0'

#### make completed successfully (08:18 (mm:ss)) ####`

**Comment by abhishekr700** [comment]
Which toolchain is being used at your end ?
uber is popping the error for me.

**Comment by luk1337** [comment]
Default CM 4.9 aarch64 toolchain.

**Comment by abhishekr700** [comment]
I wil test and close this issue ASAP

**Comment by abhishekr700** [comment]
I'm sorry to ask again, but by cm 4.9 you mean the google ndk right?

**Comment by luca020400** [comment]
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 branch android-6.0.1_r46

**Comment by luca020400** [comment]
Sync again, we merged the old fix

**Comment by abhishekr700** [comment]
Okk I will sync , but still how could it be compiled without those two break statements as in previous fix.

**Comment by luca020400** [comment]
I don't know :P

**Comment by luk1337** [comment]
I compiled it without them on two machines.

**Comment by abhishekr700** [comment]
luca are you sure?
I just re compiled using your toolchain and I still faced it.

**Comment by abhishekr700** [comment]
Anyways , The commit 7be6f3 resolved this issue.
